/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empleadosmanager;

import java.io.EOFException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author Lourdes
 */
public class Menu extends javax.swing.JFrame {

    EmpleadosManager emp;

    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
        emp = new EmpleadosManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AGREGAREMPLEADO = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        AGREARALEMPLEADO = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        AGREGARVENTAEMPLEADO = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigoEmpleado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMontoVenta = new javax.swing.JTextField();
        AGREGARVENTA = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LOGO = new javax.swing.JButton();
        LISTAR_EMPLEADOS = new javax.swing.JButton();
        AGREGAR_VENTA = new javax.swing.JButton();
        PAGAR_EMPLEADO = new javax.swing.JButton();
        DESPEDIR_EMPLEADO = new javax.swing.JButton();
        CREARR = new javax.swing.JButton();
        SALIR = new javax.swing.JButton();

        AGREGAREMPLEADO.setTitle("AGREGAR EMPLEADO");
        AGREGAREMPLEADO.setBackground(new java.awt.Color(255, 255, 255));
        AGREGAREMPLEADO.setLocation(new java.awt.Point(5, 5));
        AGREGAREMPLEADO.setPreferredSize(new java.awt.Dimension(395, 345));
        AGREGAREMPLEADO.setSize(new java.awt.Dimension(395, 345));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Salario:");

        AGREARALEMPLEADO.setBackground(new java.awt.Color(0, 51, 153));
        AGREARALEMPLEADO.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AGREARALEMPLEADO.setForeground(new java.awt.Color(255, 255, 255));
        AGREARALEMPLEADO.setText("AGREGAR");
        AGREARALEMPLEADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGREARALEMPLEADOActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("AGREGAR EMPLEADO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtSalario))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel5)))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AGREARALEMPLEADO)
                .addGap(77, 77, 77))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(AGREARALEMPLEADO)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AGREGAREMPLEADOLayout = new javax.swing.GroupLayout(AGREGAREMPLEADO.getContentPane());
        AGREGAREMPLEADO.getContentPane().setLayout(AGREGAREMPLEADOLayout);
        AGREGAREMPLEADOLayout.setHorizontalGroup(
            AGREGAREMPLEADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AGREGAREMPLEADOLayout.setVerticalGroup(
            AGREGAREMPLEADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        AGREGARVENTAEMPLEADO.setTitle("AGREGAR EMPLEADO");
        AGREGARVENTAEMPLEADO.setBackground(new java.awt.Color(255, 255, 255));
        AGREGARVENTAEMPLEADO.setLocation(new java.awt.Point(5, 5));
        AGREGARVENTAEMPLEADO.setPreferredSize(new java.awt.Dimension(410, 370));
        AGREGARVENTAEMPLEADO.setSize(new java.awt.Dimension(410, 370));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(460, 460));
        jPanel3.setPreferredSize(new java.awt.Dimension(460, 370));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("Codigo de Empleado:");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("Monto de la Venta:");

        AGREGARVENTA.setBackground(new java.awt.Color(153, 0, 0));
        AGREGARVENTA.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        AGREGARVENTA.setForeground(new java.awt.Color(255, 255, 255));
        AGREGARVENTA.setText("AGREGAR");
        AGREGARVENTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGREGARVENTAActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("AGREGAR VENTA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel8))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(txtMontoVenta)
                            .addComponent(AGREGARVENTA, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel10)
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMontoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(AGREGARVENTA)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout AGREGARVENTAEMPLEADOLayout = new javax.swing.GroupLayout(AGREGARVENTAEMPLEADO.getContentPane());
        AGREGARVENTAEMPLEADO.getContentPane().setLayout(AGREGARVENTAEMPLEADOLayout);
        AGREGARVENTAEMPLEADOLayout.setHorizontalGroup(
            AGREGARVENTAEMPLEADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        AGREGARVENTAEMPLEADOLayout.setVerticalGroup(
            AGREGARVENTAEMPLEADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empleados Manager");
        setBackground(new java.awt.Color(0, 102, 102));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        LOGO.setBackground(new java.awt.Color(255, 255, 255));
        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/empleadosmanager/iconoMENU3.png"))); // NOI18N
        LOGO.setToolTipText("");

        LISTAR_EMPLEADOS.setBackground(new java.awt.Color(204, 204, 204));
        LISTAR_EMPLEADOS.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        LISTAR_EMPLEADOS.setText("Listar Empleados No Despedidos");
        LISTAR_EMPLEADOS.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        LISTAR_EMPLEADOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LISTAR_EMPLEADOSActionPerformed(evt);
            }
        });

        AGREGAR_VENTA.setBackground(new java.awt.Color(204, 204, 204));
        AGREGAR_VENTA.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        AGREGAR_VENTA.setText("Agregar Venta a Empleado");
        AGREGAR_VENTA.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        AGREGAR_VENTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGREGAR_VENTAActionPerformed(evt);
            }
        });

        PAGAR_EMPLEADO.setBackground(new java.awt.Color(204, 204, 204));
        PAGAR_EMPLEADO.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        PAGAR_EMPLEADO.setText("Pagar Empleado");
        PAGAR_EMPLEADO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        PAGAR_EMPLEADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAGAR_EMPLEADOActionPerformed(evt);
            }
        });

        DESPEDIR_EMPLEADO.setBackground(new java.awt.Color(204, 204, 204));
        DESPEDIR_EMPLEADO.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        DESPEDIR_EMPLEADO.setText("Despedir Empleado");
        DESPEDIR_EMPLEADO.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        DESPEDIR_EMPLEADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DESPEDIR_EMPLEADOActionPerformed(evt);
            }
        });

        CREARR.setBackground(new java.awt.Color(255, 255, 255));
        CREARR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/empleadosmanager/agregar2.png"))); // NOI18N
        CREARR.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CREARR.setBorderPainted(false);
        CREARR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREARRActionPerformed(evt);
            }
        });

        SALIR.setBackground(new java.awt.Color(255, 255, 255));
        SALIR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/empleadosmanager/salir1.png"))); // NOI18N
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(CREARR)
                        .addGap(202, 202, 202)
                        .addComponent(LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(LISTAR_EMPLEADOS, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(AGREGAR_VENTA, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(PAGAR_EMPLEADO, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(DESPEDIR_EMPLEADO, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(216, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LOGO, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CREARR))
                .addGap(18, 18, 18)
                .addComponent(LISTAR_EMPLEADOS, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AGREGAR_VENTA, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PAGAR_EMPLEADO, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DESPEDIR_EMPLEADO, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(SALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CREARRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREARRActionPerformed
        // TODO add your handling code here:
        AGREGAREMPLEADO.setVisible(true);
    }//GEN-LAST:event_CREARRActionPerformed

    private void LISTAR_EMPLEADOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LISTAR_EMPLEADOSActionPerformed
  
    String listaEmpleados = emp.obtenerListaEmpleados();
    
    if (listaEmpleados.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No hay empleados para mostrar", "Lista de Empleados", JOptionPane.INFORMATION_MESSAGE);
    } else {
        // Mostrar la lista en un cuadro de diálogo
        JTextArea textArea = new JTextArea(listaEmpleados);
        textArea.setEditable(false);
        JScrollPane scrollPane = new JScrollPane(textArea);
        JOptionPane.showMessageDialog(this, scrollPane, "Lista de Empleados", JOptionPane.INFORMATION_MESSAGE);
    }

    }//GEN-LAST:event_LISTAR_EMPLEADOSActionPerformed

    private void AGREARALEMPLEADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGREARALEMPLEADOActionPerformed
        try {
            // Obtener la información del nuevo empleado desde los campos de texto y el date chooser
            String nombre = txtNombre.getText();
            double salario = Double.parseDouble(txtSalario.getText());

            // Agregar el nuevo empleado a EmpleadosManager
            emp.addEmployee(nombre, salario);

            // Limpiar los campos después de agregar un nuevo empleado
            txtNombre.setText("");
            txtSalario.setText("");

            // Mostrar un mensaje de éxito al usuario
            JOptionPane.showMessageDialog(this, "Empleado agregado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException e) {
            // Mostrar un mensaje de error si los datos ingresados no son válidos
            JOptionPane.showMessageDialog(this, "Error: Ingresa valores válidos", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_AGREARALEMPLEADOActionPerformed

    private void PAGAR_EMPLEADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAGAR_EMPLEADOActionPerformed
        try {
            int codigoEmpleado = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el código del empleado:"));

            // Verificar si el empleado existe antes de pagarle
            if (emp.isEmployeeActive(codigoEmpleado)) {
                // Verificar si el empleado ya ha sido pagado este mes
                if (!emp.isEmployeePayed(codigoEmpleado)) {
                    // Pagar al empleado
                    emp.payEmployee(codigoEmpleado);
                    JOptionPane.showMessageDialog(this, "Pago realizado correctamente al empleado con código " + codigoEmpleado, "Éxito", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Error: El empleado con código " + codigoEmpleado + " ya ha sido pagado este mes", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error: El empleado con código " + codigoEmpleado + " no existe o está despedido", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Ingresa un código válido", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_PAGAR_EMPLEADOActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SALIRActionPerformed

    private void AGREGAR_VENTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGREGAR_VENTAActionPerformed
        // TODO add your handling code here:
        AGREGARVENTAEMPLEADO.setVisible(true);
    }//GEN-LAST:event_AGREGAR_VENTAActionPerformed

    private void AGREGARVENTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGREGARVENTAActionPerformed
        try {
            int codigoEmpleado = Integer.parseInt(txtCodigoEmpleado.getText());
            double montoVenta = Double.parseDouble(txtMontoVenta.getText());

            // Verificar si el empleado existe antes de agregar la venta
            if (emp.isEmployeeActive(codigoEmpleado)) {
                // Agregar la venta al empleado
                emp.addSaleToEmployee(codigoEmpleado, montoVenta);
                JOptionPane.showMessageDialog(this, "Venta agregada correctamente al empleado con código " + codigoEmpleado, "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Error: El empleado con código " + codigoEmpleado + " no existe o está despedido", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Ingresa valores válidos", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AGREGARVENTAActionPerformed

    private void DESPEDIR_EMPLEADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DESPEDIR_EMPLEADOActionPerformed
    // Solicitar el código del empleado a despedir usando JOptionPane
    String codigoEmpleadoADespedirStr = JOptionPane.showInputDialog("Ingrese el código del empleado a despedir:");

    // Verificar si se ingresó un código
    if (codigoEmpleadoADespedirStr != null && !codigoEmpleadoADespedirStr.isEmpty()) {
        try {
            int codigoEmpleadoADespedir = Integer.parseInt(codigoEmpleadoADespedirStr);

            // Llamar al método para despedir al empleado
            emp.fireEmployee(codigoEmpleadoADespedir);

            // Mostrar un mensaje de éxito
            JOptionPane.showMessageDialog(this, "Empleado despedido exitosamente.");
        } catch (NumberFormatException e) {
            // Si el código ingresado no es un número válido
            JOptionPane.showMessageDialog(this, "Ingrese un código de empleado válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        // Si el usuario cancela la entrada
        JOptionPane.showMessageDialog(this, "Operación cancelada por el usuario.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
    }

        
    }//GEN-LAST:event_DESPEDIR_EMPLEADOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AGREARALEMPLEADO;
    private javax.swing.JDialog AGREGAREMPLEADO;
    private javax.swing.JButton AGREGARVENTA;
    private javax.swing.JDialog AGREGARVENTAEMPLEADO;
    private javax.swing.JButton AGREGAR_VENTA;
    private javax.swing.JButton CREARR;
    private javax.swing.JButton DESPEDIR_EMPLEADO;
    private javax.swing.JButton LISTAR_EMPLEADOS;
    private javax.swing.JButton LOGO;
    private javax.swing.JButton PAGAR_EMPLEADO;
    private javax.swing.JButton SALIR;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCodigoEmpleado;
    private javax.swing.JTextField txtMontoVenta;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
